name: Sprint Backlog
description: 特定スプリントのスプリントバックログ
title: "[Sprint Backlog] Sprint "
labels: ["sprint-backlog"]
body:
  - type: input
    id: sprint-name
    attributes:
      label: スプリント名
      placeholder: "Sprint 1 (2026-01-01〜2026-01-14)"
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: スプリントゴール
      description: このスプリントで達成したいゴール
      placeholder: "例: CLIツールの基本コマンド群を利用可能にする"
    validations:
      required: true

  - type: textarea
    id: pbis
    attributes:
      label: 対象PBI一覧
      description: このスプリントに含めるPBIのリスト
      placeholder: "- #123 [PBI] XXX\n- #124 [PBI] YYY"
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: リスク・懸念
      placeholder: "- チームメンバー不在\n- 技術的な不確実性 など"
    validations:
      required: false
