name: Sprint Task
description: スプリントバックログ用タスク（マイルストーンでスプリント管理）
title: "[SB] "
labels: ["sprint-backlog"]
body:
  - type: dropdown
    id: pbi
    attributes:
      label: 対応PBI
      description: 親となるプロダクトバックログIssueを選択
      options:
        - "#123 [PBI] ログ機能"
        - "#124 [PBI] 認証機能"
    validations:
      required: true

  - type: textarea
    id: task
    attributes:
      label: タスク詳細
      description: 具体的な作業内容（実装/テスト/ドキュメント）
      placeholder: "ログ作成APIの実装（POST /api/log）"
    validations:
      required: true

  - type: input
    id: estimate
    attributes:
      label: 見積もり
      placeholder: "3 (ストーリーポイント or 工数)"
    validations:
      required: true
