name: Sprint Backlog Item
description: スプリント内に割り当てたPBI単位のアイテム
title: "[Sprint Backlog Item] "
labels: ["sprint-backlog-item"]
body:
  - type: dropdown
    id: sprint
    attributes:
      label: 対象スプリント
      options:
        - Sprint 1
        - Sprint 2
        - Sprint 3
    validations:
      required: true

  - type: textarea
    id: pbi-link
    attributes:
      label: 元PBI / Storyリンク
      description: 関連するPBIやUser StoryのIssue番号
      placeholder: "- PBI: #123\n- Story: #45"
    validations:
      required: true

  - type: textarea
    id: work-plan
    attributes:
      label: 作業内容・タスク分解
      description: このスプリントで行う具体的な作業
      placeholder: "- 実装\n- テスト\n- ドキュメント更新 など"
    validations:
      required: true

  - type: textarea
    id: progress
    attributes:
      label: 進捗メモ
      description: 残作業、阻害要因など
      placeholder: "- 残り作業\n- ブロッカー\n- メモ"
    validations:
      required: false

  - type: input
    id: assignee
    attributes:
      label: 担当者
      placeholder: "github-id"
    validations:
      required: false
